"""
[DOMAIN: GENERIC]
Playwright Writer — generates retest scripts from enriched defect data.

Two modes controlled by SCRIPT_GENERATION in .env:
  local — Option C: deterministic template, no AI, fully private
           Produces skeleton with TODO markers — requires manual assertion writing
           Good for: air-gapped environments, strict NDA, quick reference
  cloud  — Option B: Gemini generates complete working script with assertions
           Requires GEMINI_API_KEY, data sent to Google API
           Good for: quality-first environments, actual automation

Salesforce / Shadow DOM note:
- SF LWC components use Shadow DOM — standard CSS selectors won't pierce it
- Playwright pierce syntax: page.locator("pierce/#selector")
- Aura component IDs (e.g. #\\31 2497\\:0) are dynamic — change between sessions/releases
- AI-extracted selectors from comments are hints, not guaranteed stable
- Always verify selectors manually before adding to CI
"""

import logging
import os
import re
from pathlib import Path

from agent.defect_enricher import EnrichedDefect

logger = logging.getLogger(__name__)

SCRIPTS_DIR = Path("retest/scripts")
PIERCE = "pierce/"

# ---------------------------------------------------------------------------
# Option B — Gemini system prompt
# ---------------------------------------------------------------------------

_GEMINI_SYSTEM_PROMPT = """You are a senior QA automation engineer specializing in Playwright Python.
Generate complete, working Playwright retest scripts.

RULES:
- Use pytest + playwright.sync_api
- Always import and call login: from retest.shared.sf_login import login
- Use RECORD_URL variable for navigation (already defined in script)
- Add meaningful assertions using expect() that FAIL when the bug is present
- Add wait_for_load_state("networkidle") after navigation
- Add appropriate timeouts for dynamic elements
- For Salesforce Shadow DOM use pierce syntax: page.locator("pierce/selector")
- Mark uncertain selectors with # TODO: verify selector
- Keep the script flat — no classes, no POM
- Return ONLY the test function body (def test_retest_... and its contents)
- Do NOT include imports, RECORD_URL definition, or login call — those are added by the template
"""

_GEMINI_PROMPT_TEMPLATE = """Generate a Playwright Python retest function for this bug:

ISSUE: {issue_key}
SUMMARY: {summary}
URL: {url}
STEPS TO REPRODUCE:
{steps}

EXPECTED RESULT:
{expected}

ACTUAL RESULT (the bug):
{actual}

UI ELEMENTS / SELECTORS:
{ui_elements}

ERROR MESSAGE: {error_message}

REQUIREMENTS:
- The test function must be named: test_retest_{slug}
- The test must FAIL when the bug is still present
- The test must PASS when the bug is fixed
- Add wait strategies for dynamic SF elements
- Use page.get_by_role() for buttons when no precise selector available
- If selector looks like Salesforce Aura ID (contains \\31 or slds-), use pierce/ prefix

Return ONLY the test function — no imports, no fixtures, no RECORD_URL definition.
"""

# ---------------------------------------------------------------------------
# Option C — deterministic script template
# ---------------------------------------------------------------------------

_SCRIPT_TEMPLATE = '''"""
Retest script — {issue_key}
Generated by defect-pilot ({mode})

Issue:        {issue_key}
Summary:      {summary}
Completeness: {score}/100
Generated:    {generated_at}

⚠️  BEFORE RUNNING:
    1. Verify all selectors marked with # TODO: verify selector
    2. Check test data requirements below
    3. Ensure SF_BASE_URL, SF_USERNAME, SF_PASSWORD are set in .env
    4. Run: pytest retest/scripts/{filename} -v
"""

import os
import pytest
from dotenv import load_dotenv
from playwright.sync_api import Page, expect

load_dotenv()

# ---------------------------------------------------------------------------
# Test data
# ---------------------------------------------------------------------------
{test_data_section}

# ---------------------------------------------------------------------------
# Test
# ---------------------------------------------------------------------------

{test_function}
'''

_TEST_DATA_TEMPLATE = '''# ============================================================
# TEST DATA REQUIREMENTS
# ============================================================
# {complexity_note}
#
{data_lines}
# ============================================================

{data_vars}'''


# ---------------------------------------------------------------------------
# Writer
# ---------------------------------------------------------------------------

class PlaywrightWriter:
    """
    Generates Playwright Python retest scripts from EnrichedDefect.

    Mode controlled by SCRIPT_GENERATION env var:
      local → Option C (deterministic template)
      cloud → Option B (Gemini generates test function)
    """

    def __init__(self):
        self._mode = os.getenv("SCRIPT_GENERATION", "local").lower()
        logger.info(f"[PlaywrightWriter] Initialized — mode: {self._mode}")

    def generate(self, enriched: EnrichedDefect) -> str:
        """Generate script content as string."""
        logger.info(
            f"[PlaywrightWriter] Generating script for {enriched.issue_key} "
            f"(Option {'B — Gemini' if self._mode == 'cloud' else 'C — template'})"
        )

        if self._mode == "cloud":
            test_function = self._generate_with_gemini(enriched)
            mode_label = "Option B — Gemini"
        else:
            test_function = self._generate_template_function(enriched)
            mode_label = "Option C — deterministic template"

        script = _SCRIPT_TEMPLATE.format(
            issue_key=enriched.issue_key,
            summary=enriched.summary,
            score=enriched.completeness_score,
            generated_at=_now(),
            filename=self._filename(enriched.issue_key),
            mode=mode_label,
            test_data_section=self._build_test_data(enriched),
            test_function=test_function,
        )
        return script

    def save(self, enriched: EnrichedDefect, output_dir: Path = SCRIPTS_DIR) -> Path:
        """Generate and save script to file."""
        output_dir.mkdir(parents=True, exist_ok=True)
        path = output_dir / self._filename(enriched.issue_key)
        script = self.generate(enriched)
        path.write_text(script, encoding="utf-8")
        logger.info(f"[PlaywrightWriter] Saved: {path}")
        return path

    # ------------------------------------------------------------------
    # Option B — Gemini
    # ------------------------------------------------------------------

    def _generate_with_gemini(self, enriched: EnrichedDefect) -> str:
        """Generate test function via Gemini API."""
        try:
            from ai.gemini_provider import GeminiProvider
            from config.settings import AIConfig
            import os

            config = AIConfig(
                provider="gemini",
                anthropic_api_key=None,
                anthropic_model="",
                ollama_base_url="",
                ollama_model="",
                gemini_api_key=os.getenv("GEMINI_API_KEY", ""),
                gemini_model=os.getenv("GEMINI_MODEL", "gemini-2.0-flash"),
            )
            gemini = GeminiProvider(config)

        except Exception as e:
            logger.warning(f"[PlaywrightWriter] Gemini init failed: {e} — falling back to Option C")
            return self._generate_template_function(enriched)

        steps_text = "\n".join(
            f"{i}. {step}" for i, step in enumerate(enriched.steps_to_reproduce, 1)
        ) or "Not extracted from bug report."

        ui_text = "\n".join(
            f"- {el}" for el in enriched.ui_elements
        ) or "Not extracted."

        prompt = _GEMINI_PROMPT_TEMPLATE.format(
            issue_key=enriched.issue_key,
            summary=enriched.summary,
            url=self._clean_url(enriched.url or "Unknown"),
            steps=steps_text,
            expected=enriched.expected_result or "Not extracted.",
            actual=enriched.actual_result or "Not extracted.",
            ui_elements=ui_text,
            error_message=enriched.error_message or "Not visible.",
            slug=self._slug(enriched.issue_key),
        )

        logger.info("[PlaywrightWriter] Calling Gemini for script generation...")
        try:
            response = gemini.complete(
                prompt=prompt,
                system_prompt=_GEMINI_SYSTEM_PROMPT,
            )
            # Strip markdown code fences if Gemini wraps output
            code = response.content.strip()
            code = re.sub(r'^```python\s*', '', code)
            code = re.sub(r'^```\s*', '', code)
            code = re.sub(r'\s*```$', '', code)
            logger.info("[PlaywrightWriter] Gemini script generated successfully")
            return code.strip()
        except Exception as e:
            logger.warning(f"[PlaywrightWriter] Gemini call failed: {e} — falling back to Option C")
            return self._generate_template_function(enriched)

    # ------------------------------------------------------------------
    # Option C — deterministic template
    # ------------------------------------------------------------------

    def _generate_template_function(self, enriched: EnrichedDefect) -> str:
        """Generate test function from deterministic template."""
        selectors = self._index_selectors(enriched.ui_elements)
        lines = []
        lines.append(f"def test_retest_{self._slug(enriched.issue_key)}(page: Page) -> None:")
        lines.append(f'    """')
        lines.append(f"    Retest for {enriched.issue_key}: {enriched.summary}")
        lines.append(f"")
        lines.append(f"    Expected result:")
        lines.append(f"    {enriched.expected_result or 'Not extracted'}")
        lines.append(f"")
        lines.append(f"    Actual result (bug):")
        lines.append(f"    {enriched.actual_result or 'Not extracted'}")
        lines.append(f'    """')
        lines.append(f"    # --- Login ---")
        lines.append(f"    from retest.shared.sf_login import login")
        lines.append(f"    login(page)")
        lines.append(f"")
        lines.append(f"    # --- Navigate ---")
        lines.append(f"    if not RECORD_URL:")
        lines.append(f'        pytest.skip("RETEST_URL not set — provide record URL to run this test")')
        lines.append(f"    page.goto(RECORD_URL)")
        lines.append(f'    page.wait_for_load_state("networkidle")')
        lines.append(f"")
        lines.append(f"    # --- Steps ---")

        if not enriched.steps_to_reproduce:
            lines.append(f"    # TODO: no steps extracted from bug report — add manually")
        else:
            for i, step in enumerate(enriched.steps_to_reproduce, 1):
                lines.append(f"    # Step {i}: {step}")
                action = self._map_step_to_action(step, selectors)
                lines.append(f"    {action}")
                lines.append(f"")

        lines.append(f"    # --- Assert ---")
        lines.append(f"    # TODO: add assertion")
        lines.append(f"    # Expected: {enriched.expected_result or 'not extracted'}")
        lines.append(f"    #")
        lines.append(f"    # Examples:")
        lines.append(f'    # expect(page.locator("button")).to_be_enabled()')
        lines.append(f'    # expect(page.locator(".error-message")).not_to_be_visible()')
        lines.append(f'    # expect(page).to_have_url(RECORD_URL)')
        lines.append(f"    pass  # remove when assertion is added")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Test data section (shared by both options)
    # ------------------------------------------------------------------

    def _build_test_data(self, enriched: EnrichedDefect) -> str:
        url = self._clean_url(enriched.url or "")
        has_url = bool(url) and url.lower() not in ("unknown", "nie podano", "")
        needs_fresh = self._needs_fresh_data(enriched)
        record_id = self._extract_sf_record_id(url) if has_url else None
        record_type = self._extract_sf_record_type(url) if has_url else None

        if needs_fresh:
            complexity_note = (
                "⚠️  COMPLEX: This test may require fresh test data.\n"
                "# The record from the bug report may be stale (closed, converted, or deleted).\n"
                "# Options:\n"
                "#   A) Use --url flag to provide a fresh record URL\n"
                "#   B) Create a new record manually and update RECORD_URL below\n"
                "#   C) Add setup fixture to create data programmatically"
            )
        else:
            complexity_note = "Simple navigation test — existing record URL should be sufficient."

        data_lines = []
        data_vars = []

        if has_url:
            data_lines.append(f"URL from bug report: {url}")
            if record_id and record_type:
                data_lines.append(f"Record type: {record_type} | ID: {record_id}")
                data_lines.append("WARNING: This ID is hardcoded — verify it still exists before running.")
            data_vars.append(f'RECORD_URL = os.getenv("RETEST_URL", "{url}")')
            data_vars.append('# Override: RETEST_URL="https://..." pytest retest/scripts/...')
        else:
            data_lines.append("No URL extracted from bug report.")
            data_lines.append("Set RETEST_URL environment variable before running.")
            data_vars.append('RECORD_URL = os.getenv("RETEST_URL", "")  # TODO: set URL')

        return _TEST_DATA_TEMPLATE.format(
            complexity_note=complexity_note,
            data_lines="\n".join(f"# {line}" for line in data_lines),
            data_vars="\n".join(data_vars),
        )

    # ------------------------------------------------------------------
    # Option C helpers
    # ------------------------------------------------------------------

    def _map_step_to_action(self, step: str, selectors: dict) -> str:
        step_lower = step.lower()

        if any(w in step_lower for w in ("navigate", "go to", "open", "przejdź", "otwórz", "http")):
            return "# Navigation already handled above (page.goto(RECORD_URL))"

        for keyword, selector in selectors.items():
            if keyword.lower() in step_lower and selector:
                prefix = PIERCE if self._is_shadow_dom_selector(selector) else ""
                return f'page.locator("{prefix}{selector}").click()  # TODO: verify selector'

        if any(w in step_lower for w in ("click", "kliknij", "press", "naciśnij")):
            name_match = re.search(r'"([^"]+)"|\'([^\']+)\'', step)
            if name_match:
                name = name_match.group(1) or name_match.group(2)
                return f'page.get_by_role("button", name="{name}").click()  # TODO: verify'
            return '# TODO: add click action — element name not extracted'

        if any(w in step_lower for w in ("fill", "enter", "type", "wpisz", "wprowadź")):
            return '# TODO: page.fill("selector", "value") — field not identified'

        if any(w in step_lower for w in ("attempt", "verify", "check", "sprawdź", "potwierdź", "notice")):
            return f'# Verification step: {step}'

        return f'# TODO: map to Playwright action: "{step}"'

    def _index_selectors(self, ui_elements: list) -> dict:
        index = {}
        for element in ui_elements:
            sel_match = re.search(r'\((?:element name:|selector:)?\s*([#.>\[\]\w\\:*\s-]+)\)', element)
            if sel_match:
                selector = sel_match.group(1).strip()
                keyword = element[:sel_match.start()].strip().strip('"\'')
                index[keyword] = selector
            elif re.match(r'^[#.]|^pierce/', element):
                index[element] = element
            else:
                index[element] = ""
        return index

    def _is_shadow_dom_selector(self, selector: str) -> bool:
        if re.search(r'#\\[0-9]', selector):
            return True
        if "slds-" in selector or "runtime_sales" in selector:
            return True
        return False

    def _needs_fresh_data(self, enriched: EnrichedDefect) -> bool:
        crud_keywords = (
            "create", "add", "new", "save", "submit", "delete", "convert",
            "utwórz", "dodaj", "nowy", "zapisz", "usuń", "konwertuj",
            "opportunity", "lead", "account", "contact", "szansa", "klient",
        )
        text = " ".join([
            enriched.summary,
            enriched.actual_result,
            *enriched.steps_to_reproduce,
        ]).lower()
        return any(kw in text for kw in crud_keywords)

    # ------------------------------------------------------------------
    # Shared helpers
    # ------------------------------------------------------------------

    def _clean_url(self, url: str) -> str:
        """Strip markdown angle brackets from URL — llava returns <https://...>."""
        url = url.strip().strip("<>").strip()
        match = re.search(r'https?://[^\s<>]+', url)
        return match.group() if match else url

    def _extract_sf_record_id(self, url: str) -> str | None:
        match = re.search(r'/r/\w+/(\w{15,18})/view', url)
        return match.group(1) if match else None

    def _extract_sf_record_type(self, url: str) -> str | None:
        match = re.search(r'/r/(\w+)/\w{15,18}/view', url)
        return match.group(1) if match else None

    def _filename(self, issue_key: str) -> str:
        return f"retest_{issue_key.replace('-', '_')}.py"

    def _slug(self, issue_key: str) -> str:
        return issue_key.replace("-", "_").lower()


def _now() -> str:
    from datetime import datetime
    return datetime.now().strftime("%Y-%m-%d %H:%M")