"""
[DOMAIN: GENERIC]
Playwright Writer — generates flat retest scripts from enriched defect data.

Strategy: Option C — deterministic template + EnrichedDefect data.
No AI involved in script generation. Output is a valid Python file
with clear TODO markers where manual verification is needed.

Why flat script (not POM):
- Readable by any tester, not just automation engineers
- Easy to edit when selectors change
- TODO markers make gaps explicit — no silent failures
- Good enough for v1; POM/framework in qa-automation-framework project

Salesforce / Shadow DOM note:
- SF LWC components use Shadow DOM — standard CSS selectors won't pierce it
- Playwright pierce syntax: page.locator("pierce/#selector")
- Aura component IDs (e.g. #\\31 2497\\:0) are dynamic — change between sessions/releases
- AI-extracted selectors from comments are hints, not guaranteed stable
- Always verify selectors manually before adding to CI
"""

import logging
import os
import re
from pathlib import Path

from agent.defect_enricher import EnrichedDefect

logger = logging.getLogger(__name__)

# Output directory for generated scripts
SCRIPTS_DIR = Path("retest/scripts")

# Playwright pierce selector prefix for Shadow DOM
PIERCE = "pierce/"


# ---------------------------------------------------------------------------
# Script template
# ---------------------------------------------------------------------------

_SCRIPT_TEMPLATE = '''"""
Retest script — {issue_key}
Generated by defect-pilot (Option C — deterministic template)

Issue:       {issue_key}
Summary:     {summary}
Completeness:{score}/100
Generated:   {generated_at}

⚠️  BEFORE RUNNING:
    1. Verify all selectors marked with # TODO: verify selector
    2. Check test data requirements below
    3. Ensure SF_BASE_URL, SF_USERNAME, SF_PASSWORD are set in .env
    4. Run: pytest retest/scripts/{filename} -v
"""

import os
import pytest
from dotenv import load_dotenv
from playwright.sync_api import Page, expect

load_dotenv()

# ---------------------------------------------------------------------------
# Test data
# ---------------------------------------------------------------------------
{test_data_section}

# ---------------------------------------------------------------------------
# Test
# ---------------------------------------------------------------------------

def test_retest_{issue_key_slug}(page: Page) -> None:
    """
    Retest for {issue_key}: {summary}

    Expected result:
    {expected_commented}

    Actual result (bug):
    {actual_commented}
    """
    # --- Login ---
    from retest.shared.sf_login import login
    login(page)

    # --- Navigate ---
{navigation_section}

    # --- Steps ---
{steps_section}

    # --- Assert ---
{assert_section}
'''

_TEST_DATA_TEMPLATE = '''# ============================================================
# TEST DATA REQUIREMENTS
# ============================================================
# {complexity_note}
#
{data_lines}
# ============================================================

{data_vars}'''


# ---------------------------------------------------------------------------
# Writer
# ---------------------------------------------------------------------------

class PlaywrightWriter:
    """
    Generates flat Playwright Python retest scripts from EnrichedDefect.

    No AI calls — pure template + heuristic mapping of enriched fields
    to Playwright actions. Gaps are marked with # TODO comments.
    """

    def __init__(self):
        logger.info("[PlaywrightWriter] Initialized — Option C (deterministic template)")

    def generate(self, enriched: EnrichedDefect) -> str:
        """
        Generate a Playwright retest script.

        Args:
            enriched: EnrichedDefect from DefectEnricher

        Returns:
            Python script content as string
        """
        logger.info(f"[PlaywrightWriter] Generating script for {enriched.issue_key}")

        script = _SCRIPT_TEMPLATE.format(
            issue_key=enriched.issue_key,
            summary=enriched.summary,
            score=enriched.completeness_score,
            generated_at=_now(),
            filename=self._filename(enriched.issue_key),
            issue_key_slug=self._slug(enriched.issue_key),
            test_data_section=self._build_test_data(enriched),
            expected_commented=self._comment_block(enriched.expected_result or "Not extracted"),
            actual_commented=self._comment_block(enriched.actual_result or "Not extracted"),
            navigation_section=self._build_navigation(enriched),
            steps_section=self._build_steps(enriched),
            assert_section=self._build_assert(enriched),
        )

        return script

    def save(self, enriched: EnrichedDefect, output_dir: Path = SCRIPTS_DIR) -> Path:
        """
        Generate script and save to file.

        Args:
            enriched: EnrichedDefect from DefectEnricher
            output_dir: Directory to save script (default: retest/scripts/)

        Returns:
            Path to saved script
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        path = output_dir / self._filename(enriched.issue_key)
        script = self.generate(enriched)
        path.write_text(script, encoding="utf-8")
        logger.info(f"[PlaywrightWriter] Saved: {path}")
        return path

    # ------------------------------------------------------------------
    # Private builders
    # ------------------------------------------------------------------

    def _clean_url(self, url: str) -> str:
        """Strip markdown angle brackets from URL.
        llava sometimes returns <https://...> instead of https://...
        """
        import re as _re
        url = url.strip().strip("<>").strip()
        # Also handle cases like <https://...> inside text
        match = _re.search(r'https?://[^\s<>]+', url)
        return match.group() if match else url

    def _build_test_data(self, enriched: EnrichedDefect) -> str:
        """Build test data requirements section."""
        url = self._clean_url(enriched.url or "")
        has_url = bool(url) and url.lower() not in ("unknown", "nie podano", "")

        # Detect hardcoded record IDs in URL (Salesforce pattern: /r/Object/ID/view)
        record_id = self._extract_sf_record_id(url) if has_url else None
        record_type = self._extract_sf_record_type(url) if has_url else None

        # Assess data complexity — does this test need fresh data?
        needs_fresh_data = self._needs_fresh_data(enriched)

        if needs_fresh_data:
            complexity_note = (
                "⚠️  COMPLEX: This test may require fresh test data.\n"
                "# The record from the bug report may be stale (closed, converted, or deleted).\n"
                "# Options:\n"
                "#   A) Use --url flag to provide a fresh record URL\n"
                "#   B) Create a new record manually and update RECORD_URL below\n"
                "#   C) Add setup fixture to create data programmatically"
            )
        else:
            complexity_note = "Simple navigation test — existing record URL should be sufficient."

        data_lines = []
        data_vars = []

        if has_url:
            data_lines.append(f"# URL from bug report: {url}")
            if record_id and record_type:
                data_lines.append(f"# Record type: {record_type} | ID: {record_id}")
                data_lines.append("# WARNING: This ID is hardcoded — verify it still exists before running.")
            data_vars.append(f'RECORD_URL = os.getenv("RETEST_URL", "{url}")')
            data_vars.append('# Override at runtime: RETEST_URL="https://..." pytest retest/scripts/...')
        else:
            data_lines.append("# No URL extracted from bug report.")
            data_lines.append("# Set RETEST_URL environment variable before running.")
            data_vars.append('RECORD_URL = os.getenv("RETEST_URL", "")  # TODO: set URL')

        return _TEST_DATA_TEMPLATE.format(
            complexity_note=complexity_note,
            data_lines="\n".join(f"# {line}" if not line.startswith("#") else line for line in data_lines),
            data_vars="\n".join(data_vars),
        )

    def _build_navigation(self, enriched: EnrichedDefect) -> str:
        """Build navigation step."""
        lines = []
        lines.append('    if not RECORD_URL:')
        lines.append('        pytest.skip("RETEST_URL not set — provide record URL to run this test")')
        lines.append('    page.goto(RECORD_URL)')
        lines.append('    page.wait_for_load_state("networkidle")')
        return "\n".join(lines)

    def _build_steps(self, enriched: EnrichedDefect) -> str:
        """Map enriched steps to Playwright actions using heuristics."""
        if not enriched.steps_to_reproduce:
            return '    # TODO: no steps extracted from bug report — add manually'

        lines = []
        selectors = self._index_selectors(enriched.ui_elements)

        for i, step in enumerate(enriched.steps_to_reproduce, 1):
            lines.append(f"    # Step {i}: {step}")
            action = self._map_step_to_action(step, selectors)
            lines.append(f"    {action}")
            lines.append("")

        return "\n".join(lines).rstrip()

    def _build_assert(self, enriched: EnrichedDefect) -> str:
        """Build assertion section — always TODO for v1."""
        lines = [
            "    # TODO: add assertion",
            f"    # Expected: {enriched.expected_result or 'not extracted'}",
            "    #",
            "    # Examples:",
            '    # expect(page.locator("button")).to_be_enabled()',
            '    # expect(page.locator(".error-message")).not_to_be_visible()',
            '    # expect(page).to_have_url(RECORD_URL)',
            "    pass  # remove when assertion is added",
        ]
        return "\n".join(f"    {line}" if not line.startswith("    ") else line for line in lines)

    def _map_step_to_action(self, step: str, selectors: dict[str, str]) -> str:
        """
        Heuristic mapping of natural language step to Playwright action.

        Priority:
        1. URL navigation detected → page.goto()
        2. Known selector from ui_elements → page.click(selector)
        3. Button/link name detected → page.get_by_role()
        4. Fill/type detected → page.fill()
        5. Fallback → TODO comment
        """
        step_lower = step.lower()

        # Navigation — skip if this is just navigating to the record URL (already done in Navigate section)
        if any(w in step_lower for w in ("navigate", "go to", "open", "przejdź", "otwórz", "http")):
            url_match = re.search(r'https?://\S+', step)
            if url_match:
                return f'# Navigation already handled above (page.goto(RECORD_URL))'
            return '# Navigation already handled above (page.goto(RECORD_URL))'

        # Click with known selector
        for keyword, selector in selectors.items():
            if keyword.lower() in step_lower:
                if self._is_shadow_dom_selector(selector):
                    return (
                        f'page.locator("{PIERCE}{selector}").click()'
                        f'  # TODO: verify selector (Salesforce Shadow DOM)'
                    )
                return f'page.locator("{selector}").click()  # TODO: verify selector'

        # Click by role/name
        if any(w in step_lower for w in ("click", "kliknij", "press", "naciśnij")):
            # Try to extract button/element name from step
            name_match = re.search(
                r'"([^"]+)"|\'([^\']+)\'|button\s+(\w[\w\s]+)',
                step, re.IGNORECASE
            )
            if name_match:
                name = next(g for g in name_match.groups() if g)
                return f'page.get_by_role("button", name="{name}").click()  # TODO: verify'
            return '# TODO: add click action — element name not extracted'

        # Fill / type
        if any(w in step_lower for w in ("fill", "enter", "type", "wpisz", "wprowadź")):
            return '# TODO: page.fill("selector", "value")  — field not identified'

        # Attempt / verify — usually not an action
        if any(w in step_lower for w in ("attempt", "verify", "check", "sprawdź", "potwierdź")):
            return f'# Verification step: {step}'

        return f'# TODO: map to Playwright action: "{step}"'

    def _index_selectors(self, ui_elements: list[str]) -> dict[str, str]:
        """
        Build keyword → selector index from ui_elements list.
        Extracts CSS selectors and maps them to readable keywords.
        """
        index = {}
        for element in ui_elements:
            # Extract selector if present in parentheses: "Button (selector: #id)"
            sel_match = re.search(r'\((?:element name:|selector:)?\s*([#.>\[\]\w\\:*\s-]+)\)', element)
            if sel_match:
                selector = sel_match.group(1).strip()
                keyword = element[:sel_match.start()].strip().strip('"\'')
                index[keyword] = selector
            # Raw CSS selector
            elif re.match(r'^[#.]|^pierce/', element):
                index[element] = element
            # Plain name — use as get_by_role hint
            else:
                index[element] = ""
        return index

    def _is_shadow_dom_selector(self, selector: str) -> bool:
        """Detect Salesforce/LWC Shadow DOM selectors."""
        # Aura dynamic IDs: #\31 2497\:0, numeric escaped IDs
        if re.search(r'#\\[0-9]', selector):
            return True
        # SLDS class names
        if "slds-" in selector or "runtime_sales" in selector:
            return True
        return False

    def _needs_fresh_data(self, enriched: EnrichedDefect) -> bool:
        """
        Heuristic: does this retest likely need fresh test data?
        Looks for CRUD keywords in steps and summary.
        """
        crud_keywords = (
            "create", "add", "new", "save", "submit", "delete", "convert",
            "utwórz", "dodaj", "nowy", "zapisz", "usuń", "konwertuj",
            "opportunity", "lead", "account", "contact", "szansa", "klient",
        )
        text = " ".join([
            enriched.summary,
            enriched.actual_result,
            *enriched.steps_to_reproduce,
        ]).lower()
        return any(kw in text for kw in crud_keywords)

    def _extract_sf_record_id(self, url: str) -> str | None:
        """Extract Salesforce record ID from URL: /r/Object/ID/view"""
        match = re.search(r'/r/\w+/(\w{15,18})/view', url)
        return match.group(1) if match else None

    def _extract_sf_record_type(self, url: str) -> str | None:
        """Extract Salesforce object type from URL: /r/Lead/ID/view"""
        match = re.search(r'/r/(\w+)/\w{15,18}/view', url)
        return match.group(1) if match else None

    def _comment_block(self, text: str) -> str:
        """Format multi-line text as comment-safe string."""
        return "\n    #     ".join(text.splitlines()) if text else "not extracted"

    def _filename(self, issue_key: str) -> str:
        return f"retest_{issue_key.replace('-', '_')}.py"

    def _slug(self, issue_key: str) -> str:
        return issue_key.replace("-", "_").lower()


def _now() -> str:
    from datetime import datetime
    return datetime.now().strftime("%Y-%m-%d %H:%M")